/** @type {import('@bacons/apple-targets/app.plugin').Config} */
// Declares the thin iOS Share Extension target (ADR-0008, issue #112) for
// @bacons/apple-targets, so the target is regenerated by `expo prebuild` rather
// than hand-edited into the Xcode project. The activation rule and the
// "Add to On the Road" action title live in the sibling Info.plist, which is
// authored to match — and pinned by a test to — lib/share-extension.ts. `exportJs`
// stays false: the extension is a native handoff shim with no React Native.
module.exports = {
  type: 'share',
  name: 'share',
  // Mirrors SHARE_ACTION_TITLE in lib/share-extension.ts (asserted by its tests).
  displayName: 'Add to On the Road',
  // Appended to the main app's bundle id: com.anonymous.on-the-road.share.
  bundleIdentifier: '.share',
  // Match the app's iOS deployment target (app.json → expo-build-properties).
  deploymentTarget: '26.0',
  exportJs: false,
  // The App Group the extension hands captures off through (ADR-0008). Declared
  // explicitly so both targets share it (auto-inheritance from the app's
  // entitlements didn't reach this target); must match app.json's group and the
  // APP_GROUP constant in lib/share-bridge.ts.
  entitlements: {
    'com.apple.security.application-groups': ['group.com.anonymous.on-the-road'],
  },
};
